# Generated by Django 6.0.7 on 2026-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cozyy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="verification_token",
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
